# 使用轻量级的 Python Alpine 镜像
FROM python:3.12-alpine

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories

# 设置工作目录
WORKDIR /app

# 设置 Python 环境变量
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN mkdir -p /run/nginx
COPY nginx.conf /etc/nginx/nginx.conf

# 安装依赖库
RUN apk update && apk add --no-cache \
    python3-dev \
    nginx

# 安装 Python 依赖
COPY requirements.txt .
RUN pip install -r requirements.txt -i https://mirrors.ustc.edu.cn/pypi/simple

# 复制 Flask 应用
COPY app/ .

COPY flag.sh /etc/init.sh
RUN chmod +x /etc/init.sh
EXPOSE 80


# 启动 Flask 应用
CMD ["sh", "/etc/init.sh"]