# 使用 node:20-alpine 作为基础镜像
FROM node:20-alpine

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories

# 设置工作目录
WORKDIR /app

RUN apk update && apk add --no-cache \
    nginx

RUN mkdir -p /run/nginx
COPY nginx.conf /etc/nginx/nginx.conf

COPY app/ .

# 安装依赖
RUN npm install

COPY flag.sh /etc/init.sh
RUN chmod +x /etc/init.sh
EXPOSE 80

# 启动 Flask 应用
CMD ["sh", "/etc/init.sh"]