# 使用轻量级的 Python Alpine 镜像
FROM python:3.12-alpine

# 设置工作目录
WORKDIR /app

# 设置 Python 环境变量
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# 安装依赖库
RUN apk update && apk add --no-cache \
    python3-dev

# 安装 Python 依赖
COPY requirements.txt .
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

# 复制 Flask 应用
COPY src/ ./

COPY flag.sh /etc/init.sh
RUN chmod +x /etc/init.sh
EXPOSE 80

# 启动 Flask 应用
CMD ["sh", "/etc/init.sh"]